name: Deploy Javadoc

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: master
          java-version: 15
          target-folder: docs
          project: maven
          custom-command: mvn javadoc:javadoc -Dshow=private -Ddoctitle="<img alt="Stir" width="250" src="https://raw.githubusercontent.com/john-amiscaray/Stir/master/assets/logo.png">"
